// Constructor EllipseLogo is imported.
const EllipseLogo = require("./ellipse");

// A testing suite for EllipseLogo is created.
describe("Test for ellipse logo generation.", () => {
    // A test is created to check that the resulting svg template is correct
    describe("The SVG code generated by the ellipse logo generation", () => {
      it("should match the expected SVG code for ellipse logo.", () => {
        const textColour = "white";
        const textValue = "WWW";
        const backgroundColour = "black";
        const logo = new EllipseLogo(textValue, textColour, backgroundColour);
        const expectedSVG =
`
<svg version="1.1" width="300" height="200" xmlns="http://www.w3.org/2000/svg">
<ellipse cx="150" cy="100" rx="100" ry="50" fill="black" />
<text x="150" y="125" font-size="60" text-anchor="middle" fill="white">WWW</text>
</svg>

`;
        expect(logo.generateEllipselogo()).toEqual(expectedSVG)

      });
    });
  });
  