// Constructor SquareLogo is imported.
const SquareLogo = require("./square");

// A testing suite for SquareLogo is created.
describe("Test for square logo generation.", () => {
    // A test is created to check that the resulting svg template is correct
    describe("The SVG code generated by the square logo generation", () => {
      it("should match the expected SVG code for square logo.", () => {
        const textColour = "white";
        const textValue = "WWW";
        const backgroundColour = "black";
        const logo = new SquareLogo(textValue, textColour, backgroundColour);
        const expectedSVG =
`
<svg version="1.1" width="300" height="200" xmlns="http://www.w3.org/2000/svg">
<rect x="60" y="10" rx="20" ry="20" width="180" height="180" fill="black" />
<text x="150" y="125" font-size="60" text-anchor="middle" fill="white">WWW</text>
</svg>

`;
        expect(logo.generateSquarelogo()).toEqual(expectedSVG)

      });
    });
  });
  