// Constructor TriangleLogo is imported.
const TriangleLogo = require("./triangle");

// A testing suite for TriangleLogo is created.
describe("Test for triangle logo generation.", () => {
    // A test is created to check that the resulting svg template is correct
    describe("The SVG code generated by the triangle logo generation", () => {
      it("should match the expected SVG code for triangle logo.", () => {
        const textColour = "white";
        const textValue = "WWW";
        const backgroundColour = "black";
        const logo = new TriangleLogo(textValue, textColour, backgroundColour);
        const expectedSVG =
`
<svg version="1.1" width="300" height="200" xmlns="http://www.w3.org/2000/svg">
<polygon points="50,180 150,20 250,180" fill="black" />
<text x="150" y="125" font-size="35" text-anchor="middle" fill="white">WWW</text>
</svg>

`;
        expect(logo.generateTrianglelogo()).toEqual(expectedSVG)

      });
    });
  });
  